### ISSUE TITLE
Please publish to an artifact repository

### ISSUE THREAD

**Issue by dasmb** [honeycombio/libhoney-java#1]
It is unusual for a JVM library not to be published to a public Maven compatible artifact repository. Without this, it is significantly more effort to introduce the library, and thus the Honeycomb product, into a java project. Indeed: I have an SBT artifact resolution problem that is preventing us from moving forward with our Honeycomb trial -- basically, once a one of our libraries takes a dependency on the lib-honey jar any service which includes that library will no longer build.

**Comment by zachradtka** [comment]
Sorry about not publishing to the maven repository. I will have that fixed shortly.

**Comment by zachradtka** [comment]
I just pushed to Maven Central, it will take a few hours to be indexed, but I will update you when I see it is available.

**Comment by zachradtka** [comment]
libhoney-java is now available on maven central.
