### ISSUE TITLE
org.slf4j classes are included in the libhoney jar

### ISSUE THREAD

**Issue by timvlaer** [honeycombio/libhoney-java#11]
My service is using slf4j as a logging facade. It turns out that the libhoney jar contains the exact same classes. This can cause issues if the version of the service and libhoney is not the same.
```
[WARNING] slf4j-api-1.7.25.jar, libhoney-java-1.0.6.jar define 34 overlapping classes: 
[WARNING]   - org.slf4j.helpers.SubstituteLogger
[WARNING]   - org.slf4j.helpers.NamedLoggerBase
[WARNING]   - org.slf4j.helpers.NOPMDCAdapter
[WARNING]   - org.slf4j.MarkerFactory
[WARNING]   - org.slf4j.helpers.BasicMarker
...
```
(In this case the version is exactly the same I noticed, but that's hard to tell without the source maven pom file) 

I wonder what made you decide to include those dependencies in the jar? Why not define the slf4j as a regular maven dependency?

I see you also copied a couple of other dependencies to a custom package. It avoids conflicts with regular client dependencies, but this makes the honeycomb jar unnecessary heavy, right? 
```xml
 <relocation>
   <pattern>org.apache.http</pattern>
   <shadedPattern>io.honeycomb.libhoney.shaded.org.apache.http</shadedPattern>
</relocation>
<relocation>
   <pattern>org.apache.commons</pattern>
   <shadedPattern>io.honeycomb.libhoney.shaded.org.apache.commons</shadedPattern>
</relocation>
<relocation>
   <pattern>com.fasterxml.jackson</pattern>
   <shadedPattern>io.honeycomb.libhoney.shaded.com.fasterxml.jackson</shadedPattern>
</relocation>
```

**Comment by asdvalenzuela** [comment]
Thanks for filing this! I'm taking a look and will get back to you in the next few days.

**Comment by asdvalenzuela** [comment]
slf4j was added as a normal dependency in https://github.com/honeycombio/libhoney-java/pull/12.

In the case of the other dependencies, it does make the jar heavier, but we thought it was worth it to reduce maintenance issues and makes dependency management easier.
