### ISSUE TITLE
Incomplete documentation, missing artifact in maven. 

### ISSUE THREAD

**Issue by mhat** [honeycombio/libhoney-java#3]
Note that group/name/version are missing ...

<img width="926" alt="screen shot 2018-07-14 at 9 23 37 am" src="https://user-images.githubusercontent.com/973/42726347-c9d8a252-8747-11e8-9641-15f9a492a277.png">

Note that the last artifact was `0.0.1` from ~2017. Examples and documents refer to `1.0.0-SNAPSHOT`. 

<img width="568" alt="screen shot 2018-07-14 at 9 23 28 am" src="https://user-images.githubusercontent.com/973/42726348-cb7caee6-8747-11e8-8d56-ccc4dfe56898.png">

**Comment by asdvalenzuela** [comment]
Release 1.0.0 is now up in Maven Central Repository.
