### ISSUE TITLE
Add support for markers

### ISSUE THREAD

**Issue by KaoruDev** [honeycombio/libhoney-java#39]
Would anyone be against adding support for markers?

https://docs.honeycomb.io/api/markers/

**Comment by KaoruDev** [comment]
I'm trying to take a swing at a PR, but it appears there might be significant changes required to get it going. I'll try to iterate the problems I see and how to potentially solve them.

1. The `BatchingHttpTransport` wraps around the HTTPClient which means I can't necessarily share it.
1. Given that Markers are typically one off requests, it doesn't make a whole sense to me to have them batched.

**Comment by KaoruDev** [comment]
## Desired Capabilities
* Creating Markers
* Updating Markers

## High level proposal
I surveyed the library to get a sense of what needs to be done to support `Markers`. I think there might be non-trivial changes required to get it going. It appears to me `LibHoney` is design primarily around "fire and forget" of events. Adding support for `Markers` means setting up support for a request API in order for users to potentially make modifications to the `Marker` (selfishly this is my use-case). There are a few problems I'd like to discuss given these assumptions:

1. I'd like to continue using the `CloseableHttpAsyncClient` to avoid having multiple clients for different purposes and potentially taking up more resources from the host JVM. In order to meet this requirement I'll have to move the creation of the `CloseableHttpAsyncClient` from `BatchingHttpTransport` into `HoneyClient`.
1. Regarding method signatures, I plan to create a method in `HoneyClient` to allow users to create a `Marker` that will be initialized with the client itself to allow users to call `Marker#send`. `Marker#send` will be "fire and forget" in case the user does not care about the result of the request. `Marker#send(Callable<MarkerResponse>)` will allow users to receive information about the result. 
1. `MarkerResponse` will consist of 2 fields:
    1. Nullable String errorMessage - if `null` there was no error, otherwise the string will contain why the request failed.
    1. Marker marker - a new `Marker` with the response details from Honeycomb's API Servers, it will be initialized with the client in case users want to later update the Marker.
1. Running the `Callable` passed in from `Marker#send(Callable<MarkerResponse>)` can lead to freezing the `CloseableHttpAsyncClient` as the user may have blocking code inside of the `Callable`. If the `CloseableHttpAsyncClient`'s threads are blocked, `HoneyClient` will be unable to send events to the servers. A way to mitigate that risk is by running the `Callable` inside of a threadpool which `HoneyClient` manages. 
1. This new threadpool can be used for any method that requires running an async callback. The following will be the threadpool's default configuration, that can be reconfigured via `ResponseHandlerOptions`.
    1. Have a maximum of 5 daemon threads. 
    1. Queue will be limited to 100 `Runnables`. When the queue is full any callbacks will be dropped and a log will be written.
    1. Exceptions thrown inside of `Callable<MarkerResponse>` will be ignored and written to log.

Let me know your thoughts on the above and if there is a better way to proceed, I'm no Java master by any means, especially Java 7 :pray:.

## Things not in Scope
* Deleting Markers
* Listing Markers
* I can write comments on the methods but not sure I have the write (😉) skills to write public documentations.

**Comment by osi** [comment]
Have `Marker#send` return a `Future`. We should ask about Java 7 support - if it were possible to target Java 8, a `CompletableFuture`, would be more apt.

There's no need for a `MarkerResponse`. The `Future` will resolve to the updated `Marker`, or it will contain an exception.

There's then no problem wrt threading, as there's no `Callable`

**Comment by KaoruDev** [comment]
@osi thanks for the quick response. I do agree having the ability to return a `CompletableFuture<Marker>` would be desirable, but I'm not entirely sure if Honeycomb wants to drop Java 7 support (Nor do I know who to ask).

Returning a `Future<Marker>` means the callers would have to block a thread to get the results. I assume most would use a threadpool to retrieve the Future's value, so why not implement it on on their behalf? Alternatively, given that `Future#get` could block, why not just have `Marker#send` be a blocking method?

**Comment by osi** [comment]
Hopefully someone from HC will chime in on Java 7 compatibility. It may be the case that there was no strong need to use any Java 8 features, thus using 7. But given that it's almost 2021, I'd drop it if it were my call 😀 

Yes, one would need to use a thread pool to poll for the result of the future. However, that'd only need to be done in the case where someone does want to get a handle to the marker (your original 2nd case).

**Comment by KaoruDev** [comment]
> Yes, one would need to use a thread pool to poll for the result of the future. However, that'd only need to be done in the case where someone does want to get a handle to the marker (your original 2nd case).

Ah, fair enough, I think this is reasonable for V1. Thanks, 👍 I'll try to get a PR by EOW.

**Comment by MikeGoldsmith** [comment]
Weirdly, I am not able to set the @honeycombio/integrations-team as the assignee to get it on our things to look into / watch.

Thanks for the contribution @KaoruDev - we'll try to get you some feedback soon.

**Comment by paulosman** [comment]
Hi, @KaoruDev thanks for opening the issue! We've discussed this internally, and it's something we may add one day, but aren't planning to support in the libhoneys at the moment. We try to make sure that the SDKs follow our [SDK specification](https://docs.honeycomb.io/api/sdk-spec/), which at the moment does not consider any resources other than events. Appreciate the support for the idea, but please don't spend time on a PR at this time. Thanks!

**Comment by KaoruDev** [comment]
ah ok, thx @paulosman for the verification. I spent the morning looking at how the Library was structured and introducing support for `Marker` is definitely non-trivial. Glad you reached out before I had a PR ready.
