### ISSUE TITLE
libhoney-java "thin" classfier has missing POM dependencies

### ISSUE THREAD

**Issue by rkennedy-mode** [honeycombio/libhoney-java#43]
The "thin" (unshaded) classifier of the libhoney-java library doesn't work with [the libhoney-java POM](https://search.maven.org/artifact/io.honeycomb.libhoney/libhoney-java/1.3.1/jar). This is because the POM is built for the shaded libhoney-java. As a result, the POM only declares a dependency on slf4j-api even though libhoney-java also depends on `com.fasterxml.jackson.core:jackson-[core|databind]` and `org.apache.httpcomponents:httpasyncclient`. As a result, including only the following in your POM file:

```xml
    <dependencies>
        <dependency>
            <groupId>io.honeycomb.libhoney</groupId>
            <artifactId>libhoney-java</artifactId>
            <version>1.3.1</version>
            <classifier>thin</classifier>
        </dependency>
    </dependencies>
```

will result in ClassNotFoundExceptions:

```
Exception in thread "main" java.lang.NoClassDefFoundError: com/fasterxml/jackson/core/type/TypeReference
	at io.honeycomb.libhoney.transport.impl.BatchingHttpTransport.init(BatchingHttpTransport.java:69)
	at io.honeycomb.libhoney.HoneyClient.<init>(HoneyClient.java:118)
	at io.honeycomb.libhoney.HoneyClient.<init>(HoneyClient.java:108)
	at io.honeycomb.libhoney.LibHoney.create(LibHoney.java:29)
	at ExerciseLibHoneyJava.main(ExerciseLibHoneyJava.java:18)
Caused by: java.lang.ClassNotFoundException: com.fasterxml.jackson.core.type.TypeReference
	at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:355)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
	... 5 more
```

Projects using the libhoney-java "thin" classifier are forced to additionally add libhoney-java's dependencies as `<scope>runtime</scope>` dependencies in order to avoid the exception.

Is there a strong reason for continuing providing the shaded libhoney-java artifact? Could the un-shaded version just become the only version and ship with a POM that properly identifies it's dependencies?

**Comment by alamothe** [comment]
Interesting... is "thin" artifact documented anywhere?

**Comment by rkennedy-mode** [comment]
I don't recall it being documented. I just happened to be following along in the discussion #33 to know about it.

**Comment by alamothe** [comment]
That's a shame. I'm glad I found about it here. We already had two major issues with shaded artifact, one was old version of Apache HTTP client causing deadlocks, and now https://github.com/honeycombio/libhoney-java/issues/107

Happily switched to the "thin" artifact.

**Comment by MikeGoldsmith** [comment]
Hey both - I'm sorry this got lost.

I don't feel we would want to dispose of the regular (shaded) version of the library without a major bump, but we can look into shipping separate POMs for both jars. I'll add doing that to our backlog and a short-term fix to the README of the library to indicate how to specify the missing dependencies when using the "thin" version.

**Comment by MikeGoldsmith** [comment]
I'm going to close this ticket as the two new linked tickets will track the work to publish a new POM for thin jars and remove the shaded jar.
